### ISSUE TITLE
Doesn't work due to CORS

### ISSUE THREAD

**Issue by kuba-orlik** [YunoHost-Apps/synapse-admin_ynh#21]
### Describe the bug

The app can't connect to Synapse, because the CORS settings prevent it from doing so

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.4.2.14
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 0.8.5~ynh2

### Steps to reproduce

- install the app
- open the app
- log into the app
- all views are empty
- open browser console
- see error: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix.domain.com/_synapse/admin/v1/rooms?dir=f&from=0&limit=10&order_by=name. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 302`

### Expected behavior

The CORS headers should be configured in a way that lets the app make requests to the synapse domain

**Comment by tituspijean** [comment]
Hello,

The app is partially working right now because we are waiting for the merge of the testing PR from Synapse. Can you try the instruction left here? https://github.com/YunoHost-Apps/synapse-admin_ynh/issues/20#issuecomment-1267124185

I have tested the app on a new domain and server recently, and these worked as is, without supplemental CORS instructions.

**Comment by retiolus** [comment]
Doesn't work for me

**Comment by wrapper** [comment]
I have also tried the testing branch, no difference. Any updates here?

**Comment by tytan652** [comment]
Adding `https://` to the headers seems to work

``` nginx
location /_synapse/admin {
        proxy_pass http://127.0.0.1:8008;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;

        client_max_body_size 100M;

        more_set_headers "Access-Control-Allow-Origin: https://__DOMAIN__";
}

```

**Comment by tituspijean** [comment]
The endpoint already ensures that: https://github.com/YunoHost-Apps/synapse-admin_ynh/blob/master/conf/endpoint.nginx.conf
😇

**Comment by tituspijean** [comment]
Current state of the app should be OK. Please reopen an issue if it arises. (and cleaning up all issues, this one was spread over 4 threads)
