### ISSUE TITLE
Installation doesn't work because of packages that don't want to remove (cmdtest)

### ISSUE THREAD

**Issue by tr1p0p** [YunoHost-Apps/synapse-admin_ynh#22]
After a installation of synapse and remove of dendrite, (getting sick my messages and rooms BREAK at EVERY update of dendrite, losing all without any form of recovery). I tried to install the synapse admin, but installation doesn't seem to work.

I'm running yunohost last version on a PC on a  i3-3240T CPU.

Here the logs of the failed installation. Seems it's a problem with the script want to remove dependencies that synapase-ynh-deps put in at first place. Also, maybe the fact i have a custom yarn app that run, maybe ? I install synapse before the admin.

Synapse seem to been running fine.

https://paste.yunohost.org/raw/rixuvafoma

Thanks for the help, and the good work.

**Comment by tituspijean** [comment]
> (getting sick my messages and rooms BREAK at EVERY update of dendrite, losing all without any form of recovery)

That is an unrelated issue that is most welcome, with logs, in Dendrite_ynh repository.

> yunohost last version

That is not helpful for future reference. You meant v11.0.10.2

---

Can you consider removing `cmdtest` without breaking your custom yarn app? `apt-get remove cmdtest --dry-run` would help you identify what would happen.

**Comment by tr1p0p** [comment]
Well i wonder if log of dendrite could help on the yunohost because it seem to be dendrite issues, so for the moment i just wait.. 

Sorry, yeah i should write the yunohost version.

So, i try to remove cmdtest, but it show the exact same issue with the same logs, so i think it's because of my other yarn app. but it's weird it try to remove cmdtest. Also, when i use apt to remove it also remove synapse-admin-deps. So i guess the remove script didn't get rid of this too in the process ?

**Comment by tr1p0p** [comment]
I don't understand why yunohost need a lot of volunteer work to pack app that already standardize themselves on thing like kubbernet and docker. that just.. well, doing more fragmentation, and leave a lots of app with issues and security flaws.

Like the fact synapse config on yunohost put some security flaws that you cannot do anything because admin web ui for synpase is a another app, and it don't really work.

Not even mentioning app that are two years old without update.. well fragmentation, like linux distro. And if community have not enough peoples to actually HELP EACH OTHER for that, it will be soon enough a fragmentation nightmare, it actually starting to get to that, slowly..

**Comment by ericgaspar** [comment]
I understand your frustration but remember, active volunteer packagers are not that many and the project as many apps…

Also, not going the Kubernetes/Docker route as little to do with fragmentation and will require the same amout of volunteer work...

Well, your comment has little to do with the synapse-admin issue. You should post your opinions about the project in the forum.
