### ISSUE TITLE
failed to fetch

### ISSUE THREAD

**Issue by axac** [YunoHost-Apps/synapse-admin_ynh#5]
Matériel:
freebox delta (ARM) avec une VM DEBIAN
Version de YunoHost: 4.3.6.2

Bonjour,

J'ai installé la version 0.8.3 ynh1,
j'ai accès aux différents menu, mais il n'y a aucune donnée venant de synapse, pas d'utilisateur, groupes. 
Synapse est en version 1.47.1 ynh1.
J'ai un bandeau rouge en bas avec "failed to fetch"

je ne sais pas si je peux transmettre d'autres informations.
J'ai essayé de me loguer avec différents utilisateurs.
Merci.

**Comment by axac** [comment]
Désolé je ne sais pas pourquoi, mais tout a lair de bien fonctionner ce matin.
merci !

sorry I don't know why, but everything seems to be working fine this morning. thank you !

**Comment by centralscrutinizer21** [comment]
I would like this issue to be reopenend as I am facing the same problem.
Yunohost version: 4.3.6.3 (stable)
Synapse version: 1.56.0~ynh1 (updated to the add-_synapse-perm tree)
Synapse-admin version: 0.8.5~ynh1 (updated to fix tree)
I need some help with finding the logs though
