### ISSUE TITLE
Prompt for matrix homeserver URL

### ISSUE THREAD

**Issue by nathanael-h** [YunoHost-Apps/synapse-admin_ynh#9]
Hello, 

I think we should be prompted for the homeserver URL when installing. 
I installed this, and the URL which it tries to connect me on webui is not the one of my homeserver, but the synpase-admin URL. 

What do you think?

**Comment by nathanael-h** [comment]
I changed the URL manually in the` /var/www/synapse-admin/.env` file, then restarted the systemd service and it works.

**Comment by ericgaspar** [comment]
Thanks! That should be fixed with #10

we still have this issue `NetworkError when attempting to fetch resource`, same as this I believe https://github.com/Awesome-Technologies/synapse-admin/issues/18.

Something is missing in NGINX config I guess...

**Comment by nathanael-h** [comment]
Yes thanks for this very very quick PR! I do have the same issue. Will read some docs. Maybe we should add some nginx headers somewhere...
